# Generated by Django 6.0 on 2026-01-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggregate_type", models.CharField(max_length=50)),
                ("aggregate_id", models.CharField(max_length=50)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published", models.BooleanField(default=False)),
            ],
        ),
    ]
