# Generated by Django 6.0 on 2026-02-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessnewsmodel",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="businessnewsmodel",
            name="country_code",
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterModelTable(
            name="businessnewsmodel",
            table="business_news",
        ),
    ]
