# Generated by Django 6.0 on 2026-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_businessnewsmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessnewsmodel",
            name="content",
            field=models.JSONField(),
        ),
    ]
