# Generated by Django 6.0 on 2026-03-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_businessnewsmodel_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessNewsDocModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(db_index=True, max_length=10)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "business_news_doc",
            },
        ),
    ]
