# Generated by Django 6.0 on 2026-02-03 12:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#3b82f6", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "calendar_category",
            },
        ),
        migrations.CreateModel(
            name="UserCalendarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("calendar_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("provider", models.CharField(default="google", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "google_calendar_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_calendar",
            },
        ),
        migrations.CreateModel(
            name="CalendarEventModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events",
                        to="user_calendar.categorymodel",
                    ),
                ),
            ],
            options={
                "db_table": "calendar_event",
            },
        ),
    ]
