# Generated by Django 6.0 on 2026-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_calendar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("user_id", models.IntegerField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("category_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="categorymodel",
            unique_together=set(),
        ),
    ]
