# Generated by Django 6.0 on 2026-01-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='spending_categories',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='monthly_investable_amount',
            field=models.IntegerField(default=5000000),
            preserve_default=False,
        ),
    ]
