# Generated by Django 6.0 on 2026-01-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_accountmodel_spending_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmodel",
            name="annual_income",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="country_code",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="currency",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="monthly_investable_amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
