# Generated by Django 6.0 on 2026-01-20 07:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_accountmodel_annual_income_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 1, 20, 7, 56, 40, 895608, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accountmodel",
            name="email",
            field=models.EmailField(
                default=datetime.datetime(
                    2026, 1, 20, 7, 57, 25, 310058, tzinfo=datetime.timezone.utc
                ),
                max_length=254,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
