# Generated by Django 6.0 on 2026-01-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_accountmodel_created_at_accountmodel_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountmodel",
            name="email",
        ),
    ]
