from enum import Enum


class ErrorCode(Enum):
    INVALID_PARAMETER = "INVALID_PARAMETER"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"

    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    ACCESS_DENIED = "ACCESS_DENIED"

    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    REFRESH_TOKEN_MISSING = "REFRESH_TOKEN_MISSING"
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID"

    DATA_NOT_FOUND = "DATA_NOT_FOUND"
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY"
    DATA_INTEGRITY_VIOLATION = "DATA_INTEGRITY_VIOLATION"

    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_BLOCKED = "USER_BLOCKED"
    USER_SUSPENDED = "USER_SUSPENDED"
    USER_DELETED = "USER_DELETED"

    PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT"
    PASSWORD_POLICY_VIOLATION = "PASSWORD_POLICY_VIOLATION"

    EXTERNAL_API_FAILED = "EXTERNAL_API_FAILED"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    TIMEOUT = "TIMEOUT"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

    GOOGLE_AUTH_CODE_MISSING = "GOOGLE_AUTH_CODE_MISSING"
    GOOGLE_AUTH_FAILED = "GOOGLE_AUTH_FAILED"
    GOOGLE_USERINFO_FAILED = "GOOGLE_USERINFO_FAILED"

    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"

    INTERNAL_ERROR = "INTERNAL_ERROR"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    