from enum import Enum


class ErrorCode(Enum):

    # === 400 BAD REQUEST ===
    INVALID_PARAMETER = "INVALID_PARAMETER"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT"
    PASSWORD_POLICY_VIOLATION = "PASSWORD_POLICY_VIOLATION"
    GOOGLE_AUTH_CODE_MISSING = "GOOGLE_AUTH_CODE_MISSING"

    # === 401 UNAUTHORIZED ===
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    REFRESH_TOKEN_MISSING = "REFRESH_TOKEN_MISSING"
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID"
    GOOGLE_AUTH_FAILED = "GOOGLE_AUTH_FAILED"

    # === 403 FORBIDDEN ===
    FORBIDDEN = "FORBIDDEN"
    ACCESS_DENIED = "ACCESS_DENIED"
    USER_BLOCKED = "USER_BLOCKED"
    USER_SUSPENDED = "USER_SUSPENDED"
    USER_DELETED = "USER_DELETED"

    # === 404 NOT FOUND ===
    DATA_NOT_FOUND = "DATA_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    USER_CALENDAR_NOT_FOUND = "USER_CALENDAR_NOT_FOUND"

    # === 405 METHOD NOT ALLOWED ===
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"

    # === 409 CONFLICT ===
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY"
    DATA_INTEGRITY_VIOLATION = "DATA_INTEGRITY_VIOLATION"

    # === 413 PAYLOAD TOO LARGE ===
    FILE_TOO_LARGE = "FILE_TOO_LARGE"

    # === 415 UNSUPPORTED MEDIA TYPE ===
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"

    # === 500 INTERNAL SERVER ERROR ===
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    # === 501 NOT IMPLEMENTED ===
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"

    # === 502 BAD GATEWAY ===
    EXTERNAL_API_FAILED = "EXTERNAL_API_FAILED"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    GOOGLE_USERINFO_FAILED = "GOOGLE_USERINFO_FAILED"

    # === 503 SERVICE UNAVAILABLE ===
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

    # === 504 GATEWAY TIMEOUT ===
    TIMEOUT = "TIMEOUT"